#!/usr/bin/env python3
"""
gen_fs.py — Generates a C source file containing a pre-formatted FAT12
filesystem image. The C file places the image in the .flash_fs linker
section, which CMakeLists.txt pins to FLASH_DISK_OFFSET (0x10040000) via
--section-start so picotool includes it in the normal bidule-01.uf2.

Usage: gen_fs.py <output.c>

Constants must stay in sync with usb_msc.c.
"""

import sys
import struct

FLASH_DISK_OFFSET = 512 * 1024               # must match usb_msc.c
FLASH_SIZE_BYTES  = 2 * 1024 * 1024
DISK_BLOCK_SIZE   = 512
DISK_BLOCK_COUNT  = (FLASH_SIZE_BYTES - FLASH_DISK_OFFSET) // DISK_BLOCK_SIZE

FAT_SECTOR_COUNT  = 3
ROOT_DIR_SECTORS  = 32
FORMAT_SERIAL     = bytes([0x42, 0x44, 0x01, 0x00])

# ── FAT12 image ───────────────────────────────────────────────────────────────

def make_boot_sector() -> bytes:
    bs = bytearray(512)
    bs[0:3]   = b'\xEB\x3C\x90'
    bs[3:11]  = b'MSDOS5.0'
    struct.pack_into('<H', bs, 11, 512)
    bs[13]    = 8
    struct.pack_into('<H', bs, 14, 1)
    bs[16]    = 2
    struct.pack_into('<H', bs, 17, 512)
    struct.pack_into('<H', bs, 19, DISK_BLOCK_COUNT)
    bs[21]    = 0xF8
    struct.pack_into('<H', bs, 22, FAT_SECTOR_COUNT)
    struct.pack_into('<H', bs, 24, 1)
    struct.pack_into('<H', bs, 26, 1)
    struct.pack_into('<I', bs, 28, 0)
    struct.pack_into('<I', bs, 32, 0)
    bs[36]    = 0x80
    bs[37]    = 0x00
    bs[38]    = 0x29
    bs[39:43] = FORMAT_SERIAL
    bs[43:54] = b'BIDULE01   '
    bs[54:62] = b'FAT12   '
    bs[510]   = 0x55
    bs[511]   = 0xAA
    return bytes(bs)

def make_fat() -> bytes:
    fat = bytearray(FAT_SECTOR_COUNT * 512)
    fat[0] = 0xF8
    fat[1] = 0xFF
    fat[2] = 0xFF
    return bytes(fat)

def make_root_dir() -> bytes:
    root = bytearray(ROOT_DIR_SECTORS * 512)
    root[0:11] = b'BIDULE01   '
    root[11]   = 0x08  # ATTR_VOLUME_ID
    return bytes(root)

def make_fs_image() -> bytes:
    fat = make_fat()
    return make_boot_sector() + fat + fat + make_root_dir()

# ── C emission ────────────────────────────────────────────────────────────────

def emit_c(image: bytes, path: str):
    flash_addr = 0x10000000 + FLASH_DISK_OFFSET
    lines = [
        "/* Auto-generated by tools/gen_fs.py — do not edit. */",
        f"/* FAT12 image for XIP flash address 0x{flash_addr:08X} (FLASH_DISK_OFFSET). */",
        "#include <stdint.h>",
        "",
        "/* Placed in .flash_fs by CMakeLists.txt --section-start linker option.",
        "   -u flash_fs_image prevents --gc-sections from discarding it. */",
        "__attribute__((section(\".flash_fs\"), used))",
        f"const uint8_t flash_fs_image[{len(image)}] = {{",
    ]
    for i in range(0, len(image), 16):
        chunk = image[i:i + 16]
        lines.append("    " + ", ".join(f"0x{b:02X}" for b in chunk) + ",")
    lines += ["};", ""]
    with open(path, "w") as f:
        f.write("\n".join(lines))

# ── Entry point ───────────────────────────────────────────────────────────────

def main():
    if len(sys.argv) != 2:
        sys.exit(f"Usage: {sys.argv[0]} <output.c>")

    image = make_fs_image()
    emit_c(image, sys.argv[1])
    print(f"[gen_fs] {len(image)} bytes -> {sys.argv[1]}")
    print(f"[gen_fs] boot[0:4]  = {image[:4].hex(' ')}")
    print(f"[gen_fs] boot[510:] = {image[510:512].hex(' ')}")

if __name__ == "__main__":
    main()
